// File generated by FlutterFire CLI. 
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwqI2rJCeUEbfP7Ds2Md8G_FzWgwsMOE',
    appId: '1:313273878001:web:7b33471b4c8f04803c3050',
    messagingSenderId: '313273878001',
    projectId: 'navalha-3a17e',
    authDomain: 'navalha-3a17e.firebaseapp.com',
    storageBucket: 'navalha-3a17e.appspot.com', // corrigido
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrVwiQLx70u44tWONv8aNOVO0Ez1DBgQg',
    appId: '1:313273878001:android:ae49a5c13e7150e53c3050',
    messagingSenderId: '313273878001',
    projectId: 'navalha-3a17e',
    storageBucket: 'navalha-3a17e.appspot.com', // corrigido
  );
}
